### ISSUE TITLE
GitHub Action?

### ISSUE THREAD

**Issue by xwipeoutx** [oktinaut/babylonjs-typescript-starter#3]
May not be in the realm of what you want to do with this project, but I'm learning babylon and used this as my base, and thought I'd get a GH action to build and deploy to azure blob (static site).

You can see my repo [here](https://github.com/xwipeoutx/roll-a-ballbyon) if you feel like stealing the GH Action workflow. Just does an NPM build and deploys https://github.com/xwipeoutx/roll-a-ballbyon.

Feel free to close this issue as "don't care" if you don't care - just thought I'd shoot it through

**Comment by oktinaut** [comment]
Sorry for the late reply. I agree that a sample workflow would be nice. 

I'll probably make one for itch.io, as I like the platform and it is often used for game jams.

**Comment by oktinaut** [comment]
It has been far too long, but I finally got around to add a deployment workflow for itch.io.

I might add other hosting providers in the future (if the hosting is free, as I don't want to create a barrier for entry), maybe just using Github Pages. But for now this should get most people started that want to create and showcase simple games.
